k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: cedi-dev-admin@cedi-dev
  currentCluster: cedi-dev
  keepMissingClusters: false
  clusters:
    cedi-dev:
      namespace:
        active: observability
        lockFavorites: false
        favorites:
        - observability
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/tn/s4s0wwrx7mgch6939pp4qp1h0000gn/T/k9s-screens-cedi
  disablePodCounting: false
