context_lookup_locations:
  - $KUBECONFIG
  - ~/.kube/config
  - ~/.kube/configs/*.yaml
picker: auto
shell: /opt/homebrew/bin/fish
post_exec_hook:
  - "set --global --export KUSH_ENVIRONMENT (tshx kube env 2>/dev/null); or set --erase KUSH_ENVIRONMENT"
